//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Darkest_Hour.Characters.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CharacterResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CharacterResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("The_Darkest_Hour.Characters.Resources.CharacterResources", typeof(CharacterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your profession:
        ///1) Rogue
        ///2) Hunter
        ///3) Warrior
        ///4) Guardian
        ///5) Mage
        ///6) Cleric
        ///.
        /// </summary>
        internal static string ChooseProfession {
            get {
                return ResourceManager.GetString("ChooseProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your characters name:
        ///.
        /// </summary>
        internal static string EnterCharacterName {
            get {
                return ResourceManager.GetString("EnterCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200 years after the ressurection and subsequent fall of King Drake,
        ///the rule of law deteroriates and darkness finds foothold in the corners
        ///of the world once more...
        ///.
        /// </summary>
        internal static string IntroPartOne {
            get {
                return ResourceManager.GetString("IntroPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} travels to Watertown, a small village on the outskirts of Ankou. Evil brews on the outskirts of Watertown and beneath its very streets. A darkness is growin in the east as evil forces that have long been forgotten return to the world. It is up to {0} to investigate and get to the bottom of the growing darkness and stop it before it spreads and consumes all of the land..
        /// </summary>
        internal static string IntroPartThree {
            get {
                return ResourceManager.GetString("IntroPartThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                   DarkTide Productions Presents....
        ///
        ///                             The Chronicles of Asku: The Darkest Hour.
        /// </summary>
        internal static string IntroPartTwo {
            get {
                return ResourceManager.GetString("IntroPartTwo", resourceCulture);
            }
        }
    }
}
